---
sidebar: sidebar
permalink: ontap-security-hardening/data-replication-encryption.html
keywords: tr-4569, ontap hardening guide, encrypted SnapMirror, SnapVault, FlexCache, pre-shared key, TLS 1.2, TLS 1.3, TLS
summary: "Use data replication encryption to TLS encrypt replication traffic for SnapMirror, SnapVault, FlexCache with a pre-shared key between ONTAP clusters."
---
= Data replication encryption
:icons: font
:imagesdir: ../media/

[.lead]
To supplement data at rest encryption, you can encrypt ONTAP data replication traffic between clusters using TLS with a pre-shared key for SnapMirror, SnapVault, or FlexCache.

When replicating data for disaster recovery, caching, or backup, you must protect that data during transport over the wire from one ONTAP cluster to another. Doing so prevents malicious man-in-the-middle attacks against sensitive data while it is in flight.

Beginning in ONTAP 9.6, cluster peering encryption provides TLS 1.2 AES-256 GCM encryption support for ONTAP data replication features such as SnapMirror, SnapVault, and FlexCache. Encryption is setup by way of a pre-shared key (PSK) between two cluster peers.

Starting in ONTAP 9.15.1, cluster peering encryption provides TLS 1.3 AES-256 GCM encryption support for ONTAP data replication features such as SnapMirror, SnapVault, and FlexCache. Encryption is setup by way of a pre-shared key (PSK) between two cluster peers.

Customers who use technologies like NSE, NVE, and NAE to protect data at rest can also use end-to-end data encryption by upgrading to ONTAP 9.6 or later to use cluster peering encryption.

Cluster peering encrypts all data between the cluster peers. For example, when using SnapMirror, all peering information as well as all SnapMirror relationships between the source and destination cluster peer are encrypted. You cannot send clear-text data between cluster peers with cluster peering encryption enabled.

Beginning with ONTAP 9.6, new cluster-peer relationships have encryption enabled by default. To enable encryption on cluster peer relationships that were created before ONTAP 9.6, you must upgrade the source and destination cluster to 9.6. In addition, you must use the `cluster peer modify` command to change both the source and destination cluster peers to use cluster peering encryption.

You can convert an existing peer relationship to use cluster peering encryption in ONTAP 9.6 as shown in the following example:
----
On the destination cluster peer:

cluster2::> cluster peer modify cluster1 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter a passphrase.

On the source cluster peer:

cluster1::> cluster peer modify cluster2 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter the same passphrase you created in the previous step.
----

//02-23-26 issue-65-chrisgeb
//6-24-24 ontapdoc-1938