---
sidebar: sidebar
permalink: ontap-security-hardening/security-hardening-overview.html
keywords: tr-4569, ontap hardening guide, security, threats, threat landscape, hardening guide, introduction
summary: "Use this guidance for ONTAP to help your organization meet prescribed security objectives for information system confidentiality, integrity, and availability."
---
= ONTAP security hardening overview
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP provides a set of controls that allow you to harden the ONTAP storage operating system, the industry's leading data management software. Use the guidance and configuration settings for ONTAP to help your organization meet prescribed security objectives for information system confidentiality, integrity, and availability.

The evolution of the current threat landscape presents an organization with unique challenges for protecting its most valuable assets: data and information. The advanced and dynamic threats and vulnerabilities we face are ever increasing in sophistication. Coupled with an increase in the effectiveness of obfuscation and reconnaissance techniques on the part of potential intruders, system managers must address the security of data and information proactively.

NOTE: Beginning in July 2024, content from the technical report _TR-4569: Security hardening guide for ONTAP_, which was previously published as a PDF, is available on docs.netapp.com. 

//6-24-24 ontapdoc-1938