---
layout: landing-page
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices
permalink: apps-dbs.html
# lead: Use only if indexpage.lead is not present in _index.yml
summary: "These technical reports provide an overview of applications and databases on ONTAP as well as recommended practices"
---
= Application and database technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP is the foundation for data management and data protection for many enterprise application and database technologies. The following technical reports provide guidance on NetApp recommended practices and implementation procedures for Microsoft SQL Server, MySQL, Oracle, and PostgreSQL.

== Microsoft SQL Server
link:https://www.netapp.com/pdf.html?item=/media/8585-tr4590.pdf[TR-4590: Best practice guide for Microsoft SQL Server with ONTAP^]
Learn how storage administrators and database administrators can successfully deploy Microsoft SQL Server on ONTAP storage.

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf[TR-4714: Best practices for Microsoft SQL Server using SnapCenter^]
Learn now to successfully deploy Microsoft SQL Server on ONTAP storage using SnapCenter technology for data protection.

== MySQL
link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf[MySQL Database on ONTAP^]
MySQL and its variants, including MariaDB and Percona, are widely used for many enterprise applications. These applications range from global social networking sites and massive ecommerce systems to SMB hosting systems containing thousands of database instances. Learn about the configuration requirements and guidance on tuning and storage configuration for deploying MySQL on ONTAP.

== Oracle
link:https://www.netapp.com/pdf.html?item=/media/8744-tr3633pdf.pdf[TR-3633: Oracle databases on ONTAP^]
Learn about the recommended practices that enable storage administrators and database administrators to successfully deploy Oracle on ONTAP storage.

link:https://www.netapp.com/pdf.html?item=/media/85630-tr-4969.pdf[TR-4969: Oracle Database Performance on AFF A-Series and C-Series^]
ONTAP is a powerful data-management platform with native capabilities that include inline compression, nondisruptive hardware upgrades, and the ability to import a LUN from a foreign storage array. Up to 24 nodes can be clustered together, simultaneously serving data through Network File System (NFS), Server Message Block (SMB), iSCSI, Fibre Channel (FC), and Nonvolatile Memory Express (NVMe) protocols. In addition, Snapshot technology is the basis for creating tens of thousands of online backups and fully operational database clones. In addition to the rich feature set of ONTAP, there are a wide variety of user requirements, including database size, performance requirements, and data protection needs. Learn about bare metal database performance using AFF storage systems, including both the A-Series and C-Series, and it covers both maximums and the practical difference between the two AFF options.

link:https://www.netapp.com/pdf.html?item=/media/85629-tr-4971.pdf[TR-4971: Virtualized Oracle database performance on AFF A-Series and C-Series^]
ONTAP is a powerful data-management platform with native capabilities that include inline compression, nondisruptive hardware upgrades, and the ability to import a LUN from a foreign storage array. Up to 24 nodes can be clustered together, simultaneously serving data through Network File System (NFS), Server Message Block (SMB), iSCSI, Fibre Channel FC), and Nonvolatile Memory Express (NVMe) protocols. In addition, Snapshot technology is the basis for creating tens of thousands of online backups and fully operational database clones. In addition to the rich feature set of ONTAP, there are a wide variety of user requirements, including database size, performance requirements, and data protection needs. Learn about virtualized database performance using AFF storage systems, including both the A-Series and C-Series, and it covers both maximums and the practical difference between the two AFF options.

link:https://www.netapp.com/pdf.html?item=/media/19666-tr-4591.pdf[TR-4591: Oracle data protection: Backup, recovery, replication, and disaster recovery^]
Learn about the recommended practices that enable storage administrators and database administrators to successfully backup, recover, replicate and provide disaster recovery to Oracle on ONTAP storage.

link:https://www.netapp.com/pdf.html?item=/media/8583-tr4592.pdf[TR-4592: Oracle on MetroCluster^]
Learn about the recommended practices, test procedures, and other considerations for operating Oracle databases on a MetroCluster synchronous replication feature. 

link:https://www.netapp.com/pdf.html?item=/media/19750-tr-4534.pdf[TR-4534: Migration of Oracle Databases to ONTAP Storage Systems^]
Learn about the overall considerations for planning a migration strategy, the three different levels in which data movement takes place, and details some of the various procedures available.

// this is also in nas-containers.html
link:https://www.netapp.com/pdf.html?item=/media/9138-tr4695.pdf[TR-4695: Database storage tiering with FabricPool^]
Learn about the benefits and configuration options of FabricPool with various databases, including the Oracle relational database management system (RDBMS).

link:https://www.netapp.com/pdf.html?item=/media/40384-tr-4899.pdf[TR-4899: Oracle database transparent application failover with SnapMirror Business Continuity^]
SnapMirror Business Continuity (SM-BC) and Oracle Real Application Cluster (RAC) can provide transparent application failover (TAF) and continuity in the face of site outages and true disasters. Learn about the configuration guidance and recommended practices of a AFF storage array with SM-BC as the storage component of Oracle RAC.

link:https://www.netapp.com/pdf.html?item=/media/21901-tr-4876.pdf[TR-4876:Oracle Multitenancy with ONTAP solution and deployment best practices^]
Learn about the solution recommended practices on how to provision, manage, and protect Oracle Multitenant databases by using ONTAP storage to maximize the benefits of both Oracle Multitenant databases and the features of ONTAP software.

== PostgreSQL
link:https://www.netapp.com/pdf.html?item=/media/17140-tr4770.pdf[TR-4770: PostgreSQL database on ONTAP^]
PostgreSQL comes with variants that include PostgreSQL, PostgreSQL Plus, and EDB Postgres Advanced Server (EPAS). PostgreSQL is typically deployed as the back-end database for multi-tier applications. It is supported by common middleware packages (such as PHP, Java, Python, Tcl/Tk, ODBC, and JDBC) and has historically been a popular choice for open-source database management systems. Learn about the configuration requirements and guidance on tuning and storage configuration for deploying PostgreSQL on ONTAP.

////
== Enterprise applications
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/common/introduction.html[ONTAP for enterprise applications]

== Microsoft SQL Server
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/mssql/introduction.html[TR-4590: Best practice guide for Microsoft SQL Server with ONTAP]
This best practice guide enables storage administrators and database administrators to successfully deploy Microsoft SQL Server on ONTAP storage.

== Oracle
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/oracle/introduction.html[Oracle on ONTAP]
This best practice guide enables storage administrators and database administrators to successfully deploy Oracle on ONTAP storage. This document is a consolidation of the content previously covered in NetApp TR-3633, TR-4591, TR-4592, TR-4534, TR-4695, and TR-4899.

== SAP HANA
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/hana/index.html[SAP HANA on ONTAP]

== PostgreSQL
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/postgres/introduction.html[PostgreSQL on ONTAP]

== MariaDB and MySQL
// git hub updated
link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/mysql/introduction.html[MariaDB and MySQL on ONTAP]
////