---
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices, SM-BC, SnapMirror Business Continuity 
permalink: business-continuity.html
summary: "These technical reports provide an overview of the business continuity in NetApp ONTAP as well as recommended practices"
---
= Business continuity technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp offers a wide range of solutions that rationalize where applications and data live to improve performance cost effectively. Data protection, replication, and continuous availability: ONTAP data management can simplify data protection with set-it-and-forget-it policy management, while delivering business continuity with MetroCluster and SnapMirror Business Continuity.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/smbc/index.html[ONTAP SnapMirror active sync] and link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html[ONTAP MetroCluster] product documentation.
====

== SnapMirror active sync (formerly SM-BC)
link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html[TR-4878: SnapMirror active sync^]
SnapMirror active sync is a continuously available storage solution with application-level granularity, available for ONTAP running on AFF or All SAN Array (ASA) storage systems, to meet the RPO 0 and RTO 0 needs of the most critical business applications.

== MetroCluster
link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf[TR-4705: NetApp MetroCluster solution architecture and design^]
This document describes high-level architecture and design concepts for MetroCluster features in ONTAP.

*MetroCluster IP*
link:http://www.netapp.com/us/media/tr-4689.pdf[TR-4689: NetApp MetroCluster IP^]
MetroCluster is a continuously available storage solution for ONTAP running on FAS and AFF systems. MetroCluster IP is the latest evolution that uses an Ethernet-based back-end storage fabric. MetroCluster IP provides a highly redundant configuration to meet the needs of the most critical business applications. MetroCluster IP is included in ONTAP and provides NAS and SAN connectivity for clients and servers that use ONTAP storage.

*MetroCluster FC*
link:https://www.netapp.com/pdf.html?item=/media/13482-tr4375.pdf[TR-4375: NetApp MetroCluster FC^]
MetroCluster provides continuous data availability across geographically separated data centers for mission-critical applications. Learn about MetroCluster FC recommended practices, design decisions, and supported configurations.