---
layout: landing-page
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices
permalink: business-continuity.html
# lead: Use only if indexpage.lead is not present in _index.yml
summary: "These technical reports provide an overview of the business continuity in NetApp ONTAP as well as recommended practices"
---
= Business continuity technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp offers a wide range of solutions that rationalize where applications and data live to improve performance cost effectively. Data protection, replication, and continuous availability: ONTAP data management can simplify data protection with set-it-and-forget-it policy management, while delivering business continuity with MetroCluster and SnapMirror Business Continuity.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/smbc/index.html[ONTAP SnapMirror Business Continuity] and link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html[ONTAP MetroCluster] product documentation.
====

// Last Update - Version - current pdf owner
// Nov 2022 - 9.12.1 - Stephen Galla
== SnapMirror Business Continuity (SM-BC)
link:https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf[TR-4878: SnapMirror Business Continuity (SM-BC)^]
SnapMirror Business Continuity (SM-BC) is a continuously available storage solution with application-level granularity, available for ONTAP running on AFF or All SAN Array (ASA) storage systems, to meet the RPO 0 and RTO 0 needs of the most critical business applications.

//link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/oracle/smbc/si.html[Single-Instance Oracle with SM-BC^]

//link:https://review.docs.netapp.com/us-en/ontap-apps-dbs_jfs/oracle/smbc/rac.html[Oracle RAC with SM-BC^]

== MetroCluster
// Apr 2023 - 9.12.1 - Stephen Galla
link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf[TR-4705: NetApp MetroCluster solution architecture and design^]
This document describes high-level architecture and design concepts for MetroCluster features in ONTAP.

*MetroCluster IP*
// May 2023 - 9.12.1 - Stephen Galla
link:http://www.netapp.com/us/media/tr-4689.pdf[TR-4689: NetApp MetroCluster IP^]
MetroCluster is a continuously available storage solution for ONTAP running on FAS and AFF systems. MetroCluster IP is the latest evolution that uses an Ethernet-based back-end storage fabric. MetroCluster IP provides a highly redundant configuration to meet the needs of the most critical business applications. MetroCluster IP is included in ONTAP and provides NAS and SAN connectivity for clients and servers that use ONTAP storage.

*MetroCluster FC*
// Oct 2021 - 9.9.1 - Cheryl George
link:https://www.netapp.com/pdf.html?item=/media/13482-tr4375.pdf[TR-4375: NetApp MetroCluster FC^]
MetroCluster provides continuous data availability across geographically separated data centers for mission-critical applications. Learn about MetroCluster FC recommended practices, design decisions, and supported configurations.