---
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices
permalink: data-protection-disaster-recovery.html
summary: "These technical reports provide an overview of the data protection and disaster recovery in ONTAP as well as recommended practices"
---
= Data protection and disaster recovery technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
SnapMirror is a cost-effective, easy-to-use unified replication solution across the data fabric. It replicates data at high speeds over LAN or WAN. You get high data availability and fast data replication for your business-critical applications, such as Microsoft Exchange, Microsoft SQL Server, and Oracle, in both virtual and traditional environments. When you replicate data to one or more ONTAP storage systems and continually update the secondary data, your data is kept current and is available whenever you need it. No external replication servers are required. 

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html[ONTAP Data protection and disaster recovery^] product documentation.
====

== SnapMirror
*SnapMirror Asynchronous*
link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015.pdf[TR-4015: SnapMirror Asynchronous configuration and best practices^]
Learn about recommended practices for configuring SnapMirror Asynchronous (SM-A) replication of volumes, consistency groups, and storage virtual machines (SVM disaster recovery).

link:https://www.netapp.com/pdf.html?item=/media/17064-tr4678.pdf[TR-4678: Data protection and backup ONTAP FlexGroup volumes^]
Learn about recommended data protection and backup for FlexGroup volumes. Topics include Snapshot copies, SnapMirror, and other data protection and backup solutions. 

*SnapMirror Synchronous*
link:https://www.netapp.com/pdf.html?item=/media/17174-tr4733.pdf[TR-4733: SnapMirror Synchronous configuration and best practices^]
Learn about recommended practices for configuring SnapMirror Synchronous (SM-S) replication.

*SnapMirror Three-Data-Center DR*
link:https://www.netapp.com/pdf.html?item=/media/19369-tr-4832.pdf[TR-4832: Three-Data-Center disaster recovery using NetApp SnapMirror for ONTAP 9.7^]
Learn about a three-data-center disaster recovery configuration using ONTAP SnapMirror technology for replication.

== Application and infrastructure with SnapMirror
// git hub updated - This is also in virtualization.html
link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-srm-overview.html[TR-4900: VMware Site Recovery Manager with ONTAP]
ONTAP has been a leading storage solution for VMware vSphere environments since its introduction into the modern data center in 2002, and it continues to add innovative capabilities to simplify management while reducing costs. Learn about recommended the ONTAP solution for VMware Site Recovery Manager (SRM), VMware's industry leading disaster recovery (DR) software, including the latest product information and recommended practices to streamline deployment, reduce risk, and simplify ongoing management.

== ONTAP cyber vault
link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html[ONTAP cyber vault^]
NetApp's ONTAP based cyber vault provides organizations with a comprehensive and flexible solution for protecting their most critical data assets. By leveraging logical air-gapping with robust hardening methodologies, ONTAP enables you to create secure, isolated storage environments that are resilient against evolving cyber threats. With ONTAP, you can ensure the confidentiality, integrity, and availability of your data while maintaining the agility and efficiency of your storage infrastructure.