---
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices
permalink: nas-containers.html
summary: "These technical reports provide an overview of the FlexCache and FlexGroup volumes in NetApp ONTAP as well as best-practice recommendations"
---
= FlexCache and FlexGroup volume technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp NAS solutions simplify data management and help you keep pace with growth while optimizing costs. ONTAP NAS solutions give you nondisruptive operations, proven efficiency, and seamless scalability within a unified architecture. Powered by  ONTAP, scale-out NAS leverages the massive ONTAP ecosystem, with a significant innovation lead and vision for aggressive future innovation.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/task_nas_flexcache.html[ONTAP FlexCache volume] and link:https://docs.netapp.com/us-en/ontap/task_nas_provision_flexgroup.html[ONTAP FlexGroup volume] product documentation.
====

== FlexCache
link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf[TR-4743: FlexCache in ONTAP^]
FlexCache is a caching technology that creates sparse, writable replicas of volumes on the same or different ONTAP clusters. It can bring data and files closer to the user for faster throughput with a smaller footprint. Learn how FlexCache can be used, the recommended practices, limits, and considerations for design and implementation.

== FlexCache write-back
link:https://docs.netapp.com/us-en/ontap/flexcache-writeback/flexcache-write-back-overview.html[FlexCache write-back^]
Introduced in ONTAP 9.15.1, FlexCache write-back is an alternate mode of operation for writing at a cache. Write-back allows the write to be committed to stable storage at the cache and acknowledged to the client without waiting for the data to make it to the origin. The data is asynchronously flushed back to the origin. The result is a globally distributed file system that enables writes to perform at near-local speeds for specific workloads and environments, offering significant performance benefits.

== FlexGroup volumes
link:https://www.netapp.com/pdf.html?item=/media/17251-tr4571a.pdf[TR-4571a: FlexGroup top ten best practices^]
This technical report is a condensed version of TR-4571: NetApp ONTAP FlexGroup volumes best practices and implementation guide for quick consumption.

link:https://www.netapp.com/pdf.html?item=/media/7337-tr4557.pdf[TR-4557: NetApp ONTAP FlexGroup volumes - A technical overview^]
Learn about FlexGroup volumes, an ONTAP scale-out NAS container, that blends near-infinite capacity with predictable, low-latency performance in metadata-heavy workloads.

link:https://www.netapp.com/pdf.html?item=/media/12385-tr4571.pdf[TR-4571: NetApp ONTAP FlexGroup volumes best practices and implementation guide^]
Learn about FlexGroup volumes, recommended practices and implementation tips. FlexGroup volumes are an evolution of ONTAP scale-out NAS containers, that blends nearly infinite capacity with predictable, low latency performance in metadata-heavy workloads.

link:https://www.netapp.com/pdf.html?item=/media/17064-tr4678.pdf[TR-4678: Data protection and backup of FlexGroup volumes^]
Learn about data protection and backup for FlexGroup volumes including Snapshot copies, SnapMirror, and other data protection and backup solutions.