---
layout: landing-page
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, NAS, best practices, best-practices
permalink: nas.html
# lead: Use only if indexpage.lead is not present in _index.yml
summary: "These technical reports provide an overview of the NFS, SMB/CIFS, S3, name services in NetApp ONTAP as well as recommended practices."
---
= NAS technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp NAS solutions simplify data management and help you keep pace with growth while optimizing costs. ONTAP NAS solutions provide for nondisruptive operations, efficiency, and seamless scalability within a unified architecture. Powered by NetApp ONTAP enterprise data management software, scale-out NAS leverages the massive ONTAP ecosystem, with a significant innovation lead and vision for aggressive future innovation.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/nas-management/index.html[ONTAP NAS storage management] and  link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[ONTAP S3 storage management] product documentation.
====

// Last Update - Version - current pdf owner
== NFS
// November 2021 - 9.10.1 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf[TR-4067: NFS in ONTAP best practice and implementation guide^]
Learn about basic concepts, support information, configuration tips, and recommended practices for NFS in ONTAP.

// April 2023 - 9.12.1 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/84595-tr-4962.pdf[TR-4962: NFSv4.2 extended attributes^]
Learn about enabling and using NFSv4.2 extended attributes in ONTAP 9.12.1 and later.

== SMB
// Oct 2016 - 9.1 - commented out by chrisgeb
//link:https://www.netapp.com/pdf.html?item=/media/10678-tr-4543.pdf[TR-4543: SMB protocol best practices^]
//This technical report details NetApp ONTAP support for SMB protocol features. Functionality is covered in terms of capabilities, requirements, implementation, and best practices.

// Oct 2016 - 9.1 - commented out by chrisgeb
// link:https://www.netapp.com/pdf.html?item=/media/16338-tr-4100.pdf[TR-4100: Nondisruptive operations with SMB file shares ONTAP 9.x^]
//This technical report details NetApp ONTAP support for nondisruptive operations (NDO) when using the SMB protocol. NDO capabilities are covered for each of the primary SMB dialects, including SMB 1, SMB 2, and SMB 3.

// Jan 2019 - 9.4 - Chow
link:https://www.netapp.com/pdf.html?item=/media/17136-tr4740.pdf[TR-4740: SMB 3.0 multichannel^]
Microsoft introduced Multichannel in the SMB 3.0 protocol with the goal of improving the SMB3 protocol by addressing the performance and reliability limitations of SMB1 and SMB2. Learn about the Multichannel feature in ONTAP, including its capabilities, recommended practices, and performance test results.

== Multiprotocol
// Apr 2021 - 9.8 - Elliot Ecton
link:https://www.netapp.com/pdf.html?item=/media/27436-tr-4887.pdf[TR-4887: Multiprotocol NAS in  ONTAP overview and best practices^]
Learn how multiprotocol NAS access works in ONTAP and the recommended practices for multiprotocol environments.

== ONTAP S3
// March 2023 - 9.12.1 - John Lantz
link:https://www.netapp.com/pdf.html?item=/media/17219-tr4814.pdf[TR-4814: S3 in ONTAP best practices^]
Learn about recommended practices for using the Amazon Simple Storage Service (S3) with ONTAP software as well as capabilities and configurations for using ONTAP as an object store with native S3 applications or as a tiering destination for FabricPool.

== Name services
// Feb 2021 - 9.4 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/19370-tr-4523.pdf[TR-4523: DNS load balancing in ONTAP^]
Learn how to configure ONTAP for use with DNS load balancing methodologies including DNS in ONTAP, various configuration methods, and recommended practices.

// Mar 2018  - 9.3 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/16328-tr-4668.pdf[TR-4668: Name services best practices guide^]
Learn about recommended practices, limits, and considerations when implementing network-attached storage (NAS) solutions such as CIFS/SMB and NFS in ONTAP.

// MAy 2021 - 9.9.1 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf[TR-4835: How to configure LDAP in ONTAP multiprotocol NAS identity management^]
Learn how to configure Lightweight Directory Access Protocol (LDAP) identity management in ONTAP for multiprotocol NAS.

== NAS security
// Jun 2021 - 9.9.1 - Elliott Ecton
link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[TR-4616: NFS Kerberos in ONTAP^]
Learn about NFS Kerberos in  ONTAP software including configuration steps with Active Directory and Red Hat Enterprise Linux (RHEL) clients.