---
permalink: nfs.html
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, NAS, best practices, best-practices
summary: "These technical reports provide an overview of the NFS, SMB/CIFS, S3, name services in NetApp ONTAP as well as recommended practices."
---
= ONTAP NAS technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp NAS solutions simplify data management and help you keep pace with growth while optimizing costs. ONTAP NAS solutions provide for nondisruptive operations, efficiency, and seamless scalability within a unified architecture. Powered by NetApp ONTAP, scale-out NAS leverages the massive ONTAP ecosystem, with a significant innovation lead and vision for aggressive future innovation.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/nas-management/index.html[ONTAP NAS storage management^] and link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[ONTAP S3 storage management^] product documentation.
====

== NFS
link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf[TR-4067: NFS in ONTAP best practice and implementation guide^]
Learn about basic concepts, support information, configuration tips, and recommended practices for NFS in ONTAP.

link:https://www.netapp.com/pdf.html?item=/media/84595-tr-4962.pdf[TR-4962: NFSv4.2 extended attributes^]
Learn about enabling and using NFSv4.2 extended attributes in ONTAP 9.12.1 and later.

== Multiprotocol
link:https://www.netapp.com/pdf.html?item=/media/27436-tr-4887.pdf[TR-4887: Multiprotocol NAS in ONTAP overview and best practices^]
Learn how multiprotocol NAS access works in ONTAP and the recommended practices for multiprotocol environments.
