settings:
  name: "ONTAP 9 Technical Reports"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
    - title: ONTAP Technical Reports
      url: /index.html
    - title: SAN
      url: /san.html
    - title: Legal notices
      url: /legal-notices.html