settings:
  name: "ONTAP 9 Technical Reports"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
    - title: ONTAP technical reports
      url: /index.html
    - title: SAN protocols
      url: /san.html
    - title: NAS protocols
      url: /nas.html
    - title: Security
      url: /security.html
    - title: FlexCache and FlexGroup volumes
      url: /nas-containers.html
    - title: Tiering
      url: /tiering.html
    - title: Storage efficiency
      url: /storage-efficiency.html
    - title: Applications and databases
      url: /apps-dbs.html
    - title: Virtualization
      url: /virtualization.html
    - title: Data protection and disaster recovery
      url: /data-protection-disaster-recovery.html
    - title: Business continuity
      url: /business-continuity.html
    - title: SnapCenter
      url: /snapcenter.html      
    - title: Networking
      url: /networking.html                                                 
    - title: Legal notices
      url: /legal-notices.html