settings:
  name: "ONTAP Technical Reports"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
    - title: ONTAP technical reports
      url: /index.html
    - title: SAN technical reports
      url: /san.html
      entries:
      - title: Best practices for modern SAN
        url: /san.html
      - title: Implementing and configuring modern SANs with NVMe-oF
        url: /san.html
      - title: ONTAP AFF All SAN Array (ASA)
        url: /san.html
    - title: NAS technical reports
      url: /nas.html
    - title: Security technical reports
      url: /security.html
    - title: FlexCache and FlexGroup volumes technical reports
      url: /nas-containers.html
    - title: Tiering technical reports
      url: /tiering.html
    - title: Storage efficiency technical reports
      url: /storage-efficiency.html
    - title: Application and database technical reports
      url: /apps-dbs.html
      entries:
      - title: Microsoft SQL Server
        url: /apps-dbs.html#microsoft-sql
      - title: Oracle
        url: /apps-dbs.html#oracle
      - title: PostgreSQL
        url: /apps-dbs.html#postgreSQL
    - title: Virtualization technical reports
      url: /virtualization.html
    - title: Data protection and disaster recovery technical reports
      url: /data-protection-disaster-recovery.html
    - title: Business continuity technical reports
      url: /business-continuity.html
    - title: SnapCenter technical reports
      url: /snapcenter.html      
    - title: Networking technical reports
      url: /networking.html
    - title: Industry solutions technical reports
      url: /industry-solutions.html
    - title: Legal notices
      url: /legal-notices.html