settings:
  name: "ONTAP technical reports"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
    - title: ONTAP technical reports
      url: /index.html
    - title: Application and database technical reports
      url: /apps-dbs.html
    - title: Business continuity technical reports
      url: /business-continuity.html
    - title: Data protection and disaster recovery technical reports
      url: /data-protection-disaster-recovery.html
    - title: FlexCache and FlexGroup volumes technical reports
      url: /nas-containers.html
    - title: Industry solutions technical reports
#Removed Industry Solutions
#      url: /industry-solutions.html
#    - title: NAS technical reports
      url: /nas.html
    - title: Networking technical reports
      url: /networking.html
    - title: SAN technical reports
      url: /san.html
    - title: Security technical reports
      url: /security.html
    - title: Security hardening guides
      url: /security-hardening-guides.html
    - title: SnapCenter technical reports
      url: /snapcenter.html      
    - title: Tiering technical reports
      url: /tiering.html
    - title: Virtualization technical reports
      url: /virtualization.html
#    - title: Change Log
#      url: /change-log-display.html
    - title: Legal notices
      url: /legal-notices.html

product-family:
  name: ONTAP
  repo: ontap-family