settings:
  name: "ONTAP 9 Technical Reports"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar: 
  entries:
  - title: Legal notices
    url: /legal-notices.html
