settings:
  name: "ONTAP technical reports"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: ONTAP technical reports
      url: /index.html
    - title: Applications and databases
      url: /apps-dbs.html
    - title: Business continuity
      url: /business-continuity.html
    - title: Data protection and disaster recovery
      url: /data-protection-disaster-recovery.html
    - title: FlexCache and FlexGroup volumes
      url: /nas-containers.html
#    - title: Industry solutions 
#      url: /industry-solutions.html
    - title: NAS
      url: /nas.html
    - title: Networking
      url: /networking.html
    - title: SAN
      url: /san.html
    - title: Security
      url: /security.html
    - title: Security hardening guides
      url: /security-hardening-guides.html
    - title: SnapCenter
      url: /snapcenter.html      
    - title: Tiering
      url: /tiering.html
    - title: Virtualization
      url: /virtualization.html
#    - title: Change Log
#      url: /change-log-display.html
    - title: Legal notices
      url: /legal-notices.html

product-family:
  name: ONTAP
  repo: ontap-family
