---
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA, best practices, best-practices
permalink: security-hardening-guides.html
summary: "These technical reports provide guidance on how to harden NetApp ONTAP as well as other ONTAP related products."
---
= Security hardening guides
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
These technical reports provide guidance on how to harden NetApp ONTAP as well as other NetApp products.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html[ONTAP security and data encryption] product documentation.
====

// Last Update - Version - current pdf owner
== Hardening guides
// Jan 2023 - 9.12.1 - Dan Tulledge
link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf[TR-4569: Security hardening guide for NetApp ONTAP^]
Learn how to configure NetApp ONTAP to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

// Apr 2023 - 9.12.1 - Ankita Dhawale - this is also in snapcenter.html
link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf[TR-4957: Security hardening guide for NetApp SnapCenter^]
Learn how to configure NetApp SnapCenter software to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

// Mar 2023 - 9.12.1 - Ankita Dhawale - this is also in snapcenter.html
link:https://www.netapp.com/pdf.html?item=/media/83591-tr-4963.pdf[TR-4963: Security hardening guide: BlueXP Cloud Backup for Applications^]
Learn how to configure NetApp Cloud Backup for Applications to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

// Feb 2023 - 9.12 - Chris Gebhardt
link:https://netapp.com/pdf.html?item=/media/78654-tr-4943.pdf[TR-4943: Security hardening guide for NetApp Active IQ Unified Manager^]
Learn how to configure NetApp Active IQ Unified Manager to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

// May 2023 - 9.12.1 - Swati Godha
link:https://www.netapp.com/pdf.html?item=/media/78941-tr-4945.pdf[TR-4945: Security hardening guide for NetApp Manageability SDK^]
Learn how to configure NetApp Manageability SDK (NMSDK) to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.