---
layout: landing-page
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA
permalink: security.html
# lead: Use only if indexpage.lead is not present in _index.yml
summary: "These technical reports provide the best-practice recommendations for securing ONTAP"
---
= Security technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

=== Zero Trust
Zero Trust traditionally has been a network-centric approach of architecting micro core and perimeter (MCAP) to protect data, services, applications, or assets with controls known as a segmentation gateway. NetApp® ONTAP® takes a data-centric approach to Zero Trust in which the storage management system becomes the segmentation gateway to protect and monitor access of our customer’s data. In particular, the FPolicy™ Zero Trust engine and the FPolicy partner ecosystem becomes a control center to gain a detailed understanding of normal and aberrant data access patterns and identify insider threats.

    - link:https://www.netapp.com/pdf.html?item=/media/19756-tr-4829.pdf[TR-4829: NetApp and Zero Trust]

=== Hardening Guides
This technical report provides guidance and configuration settings for NetApp® ONTAP® 9 to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

    - link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf[TR-4569: Security hardening guide for NetApp ONTAP 9]

This technical report provides guidance and configuration settings for NetApp® SnapCenter® software to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.

    - link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf[TR-4957: Security hardening guide for NetApp SnapCenter]

=== Ransomware
This guide covers what ransomware is; how it has evolved; and how to identify, detect early, prevent the spread, and recover as quickly as possible using the NetApp® solution for ransomware. The guidance and solutions provided in this document are designed to help organizations have cyber resilient solutions while meeting their prescribed security objectives for information system confidentiality, integrity, and availability.

    - link:https://www.netapp.com/pdf.html?item=/media/7334-tr4572.pdf[TR-4572: The NetApp Solution for Ransomware]

Many businesses rely on some use of write once, read many (WORM) data storage to meet regulatory compliance requirements or simply to add another layer to their data protection roadmap. This document discusses the integration of NetApp® SnapLock® software, the NetApp WORM solution in NetApp ONTAP® 9, into the environments that require WORM data storage.

    - link:https://www.netapp.com/pdf.html?item=/media/6158-tr4526.pdf[TR-4526: Compliant WORM storage using NetApp SnapLock]

=== Multitennancy
This report discusses the implementation of secure multitenancy using storage virtual machines (SVMs) in NetApp® ONTAP®, covering design considerations and best practices.

    - link:https://www.netapp.com/pdf.html?item=/media/16886-tr-4160.pdf[TR-4160: Secure Multitenancy in ONTAP]

=== Authentication
This document covers multifactor authentication capability for administrative access introduced in NetApp® ONTAP® 9.3 software for NetApp System Manager, Active IQ® Unified Manager and ONTAP Secure Shell (SSH) CLI authentication.

    - link:https://www.netapp.com/pdf.html?item=/media/17055-tr4647.pdf[TR-4647: Multifactor-Authentication-in-ONTAP best practices and implementation guide]

This technical report describes configuring and testing third-party SSH clients, in conjunction with ActivClient software, to authenticate an ONTAP storage administrator via the public key stored on a common access card (CAC) when it is configured in ONTAP.

    - link:https://www.netapp.com/pdf.html?item=/media/17036-tr4717.pdf[TR-4717: ONTAP SSH Authentication with a Common Access Card]

=== Key Management
This guide describes how to use the HyTrust KeyControl external key management solution for NetApp® ONTAP® 9.3 or later data management software. Topics include installation and configuration of the HyTrust KeyControl Key Management Interoperability Protocol Key Management server (KMIP server) and ONTAP 9.3 or later. This guide also offers a step-by-step example of the configuration steps, using
HyTrust KeyControl as the KMIP server.

    - link:https://www.netapp.com/pdf.html?item=/media/17044-tr4731.pdf[TR-4731: HyTrust KeyControl Key Management in ONTAP 9.3 or Later]

=== Standards
This technical report is targeted at qualified security assessors and storage administrators focused on validating a system against the PCI DSS 4.0 standard. This document provides guidance for meeting the requirements of the controls that you apply to the NetApp® ONTAP® 9 storage system. 

    - link:https://www.netapp.com/pdf.html?item=/media/17180-tr4401pdf.pdf[TR-4401: PCI-DSS 4.0 and ONTAP 9]