---
permalink: snapcenter.html
sidebar: sidebar
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices
summary: "These technical reports provide an overview of the SnapCenter with NetApp ONTAP as well as recommended practices."
---
= ONTAP SnapCenter technical reports
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
SnapCenter provides a, unified platform for application-consistent data protection and clone management. SnapCenter simplifies backup, restore, and clone lifecycle management with application-integrated workflows. Leveraging storage-based data management, SnapCenter enables increased performance and availability and reduced testing and development times.

[NOTE]
====
These technical reports expand on the link:https://docs.netapp.com/us-en/snapcenter/index.html[SnapCenter] product documentation.
====

== SnapCenter for Oracle
link:https://www.netapp.com/pdf.html?item=/media/12403-tr4700.pdf[TR-4700: SnapCenter Plug-In for Oracle database best practices^]
NetApp SnapCenter is a unified, scalable platform for Oracle-consistent data protection that automates complex operations with centralized control and oversight. Learn about the recommended practices for deploying Oracle databases with SnapCenter.

link:https://docs.netapp.com/us-en/netapp-solutions/databases/snapctr_svcs_ora.html[TR-4964: Oracle Database backup, restore and clone with SnapCenter Services]
Learn how to set up SnapCenter Services to backup, restore, and clone Oracle databases deployed to Amazon FSx for ONTAP storage and EC2 compute instances. Although it is much easier to set up and use, SnapCenter Services deliver key functionalities available through the SnapCenter interface.

== SnapCenter for Microsoft SQL Server
link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf[TR-4714: Best practices for Microsoft SQL Server using NetApp SnapCenter^]
Learn how to successfully deploy Microsoft SQL Server on NetApp storage using SnapCenter for data protection.

== SnapCenter for Microsoft Exchange Server
link:https://www.netapp.com/es/pdf.html?item=/es/media/12398-tr-4681.pdf[TR-4681: Best practices for Microsoft Exchange Server using NetApp SnapCenter^]
Learn how to successfully deploy Microsoft Exchange Server on NetApp storage using SnapCenter for data protection.

== SnapCenter for SAP HANA
link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html[TR-4614: SAP HANA backup and recovery with SnapCenter]
SnapCenter is a unified, scalable platform for application-consistent data protection for SAP HANA and other databases. SnapCenter provides centralized control and oversight, while delegating the ability for users to manage application-specific backup, restore, and clone jobs. With SnapCenter, database and storage administrators learn a single tool to manage backup, restore, and cloning operations for a variety of applications and databases.

// git hub updated
link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/amazon-fsx-overview.html[TR-4926: SAP HANA on Amazon FSx for NetApp ONTAP - Backup and recovery with SnapCenter]
Learn about the recommended practices for SAP HANA data protection on Amazon FSx for NetApp ONTAP and SnapCenter. Topics include SnapCenter concepts, configuration recommendations, and operation workflows, including configuration, backup operations, and restore and recovery operations.

// git hub updated
link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html[TR-4667: Automating SAP HANA System copy and clone operations with SnapCenter]
SnapCenter storage cloning and the option to flexibly define pre-cloning and post-cloning operations allows SAP Basis administrators to accelerate and automate SAP system copy, clone, or refresh operations. Learn now the option to choose any SnapCenter Snapshot backup at any primary or secondary storage allows you to address your most important use cases, including logical corruption, disaster recovery testing, or the refresh of an SAP QA system.

//
link:https://www.netapp.com/pdf.html?item=/media/17030-tr4719.pdf[TR-4719: SAP HANA system replication backup and recovery with SnapCenter^]
Learn how SnapCenter technology and the SAP HANA plug-in can be used for backup and recovery in an SAP HANA System Replication environment.

// git hub updated
link:https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html[TR-4667: Automating SAP HANA system copy and clone operations with SnapCenter]
The ability to create application-consistent NetApp Snapshot backups on the storage layer is the foundation for the system copy and system clone operations. Storage-based Snapshot backups are created by using the NetApp SnapCenter Plug-In for SAP HANA and interfaces provided by the SAP HANA database. SnapCenter registers Snapshot backups in the SAP HANA backup catalog so that the backups can be used for restore and recovery as well as for cloning operations.

== SnapCenter hardening guide
// this is also in snapcenter.html
link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf[TR-4957: Security hardening guide for NetApp SnapCenter^]
Learn how to configure SnapCenter to help organizations meet prescribed security objectives for information system confidentiality, integrity, and availability.