---
sidebar: sidebar
permalink: afx/afx-architecture-root-volume.html
keywords: netapp afx, root volume, boot media, nvme, m.2, cluster database
summary: "Learn how NetApp AFX virtualizes root volumes and moves boot images and cluster databases to onboard boot media."
---

= Root volume changes
:icons: font
:imagesdir: ../media/afx/

[.lead]
NetApp AFX removes physical root aggregates and uses onboard NVMe boot media for boot images and replicated cluster databases.

[[root-volume-changes]]
== Root volume changes

In NetApp ONTAP, each node is assigned a root volume, which is used for system-specific files and functions, such as log files, boot images, core files, cluster databases, and more.

In unified ONTAP, those root volumes lived on physical root aggregates. To reduce the amount of capacity the root aggregates used, they were created across data drive partitions via Advanced Disk Partitioning (ADP).

NetApp AFX removes physical aggregates from the equation, and as a result, removes the need for root aggregates and ADP to be used. Root volumes are still a concept, but they now live in virtualized areas of the capacity pool and do not require extra configuration. Additionally, root volume functionality changes. Boot images and replicated cluster databases are moved off the storage stack and into an on-board boot media found on each AFX node. Now, if access to the storage stack is lost, nodes can still boot and maintain cluster eligibility, which eases the complexity of troubleshooting.

[[onboard-boot-media]]
== Onboard boot media

NetApp AFX nodes leverage on-board boot media, which is an NVMe attached M.2 device roughly 3.8TB in size. These boot devices contain boot image files and replicated databases that are separate from the storage enclosures, which provides extra redundancy in the case of disk access issues. If the boot media fails, the node will be taken over by its HA partner and the boot media can be replaced. Once replaced, a new ONTAP image would be loaded to the device by a storage administrator and ONTAP will automatically rebuild the cluster database to restore full functionality.

[cols="1,1",frame=none,grid=none]
|===
| link:afx-architecture-cluster-scale.html[Previous: Cluster scale]
>| link:afx-remove-nodes.html[Next: How to remove AFX nodes]
|===
