---
sidebar: sidebar
permalink: afx/afx-architecture-feature-support.html
keywords: netapp afx, ontap feature support, unsupported features, metrocluster, fabricpool, block protocols
summary: "Review ONTAP features that are changed, removed, or unsupported in NetApp AFX."
---

= ONTAP feature support changes
:icons: font
:imagesdir: ../media/afx/

[.lead]
The high-performance NAS and object design of NetApp AFX changes the availability of some ONTAP features and interfaces.

[[ontap-features-that-have-been-removedare-unsupported-with-afx]]
== ONTAP features that have been removed or are unsupported with AFX

NetApp AFX is designed for high-performance NAS and object workloads – particularly (but not exclusive to) those in the AI training and inference space. With the design of NetApp AFX, some decisions were made to disable some of the features in ONTAP.

* Because of the focus on high-performance NAS and object, block workloads have been removed from the NetApp AFX solution. There is no support for FCP, iSCSI or NVMe data protocols and there are no plans to add block protocols.
* Disaggregated is synonymous to de-aggregated, which means that aggregates (at least as a physical storage administration concept) have been removed. Removal of the physical aggregate not only simplifies the management of capacity in ONTAP, but it also provides the mechanism to allow for a single pool of capacity.
* Aggregates being removed means that aggregate-specific features are also removed. Metrocluster, for instance, leverages aggregate-level mirroring for its site failover capabilities. As such, Metrocluster is also removed from NetApp AFX. Site failover functionality will instead be provided by the new SnapMirror Active-Sync for NAS feature offered in ONTAP 9.19.1GA.
* The cold data tiering feature called FabricPool is also currently unavailable to NetApp AFX since it is also aggregate-specific.
* Copy-based volume moves are also no longer necessary in NetApp AFX, due to the new capacity architecture. For more information, see link:afx-architecture-volume-moves.html#zero-copy-volume-moves[Zero-copy volume moves].
* Feature removal also means some CLI/GUI/REST API changes, so any commands or API calls for features no longer supported will also be removed.
* ZAPI is currently unavailable to NetApp AFX.
* NFS copy offload for virtualization (FlexGroup volumes with Granular Data Distribution only)

[cols="1,1",frame=none,grid=none]
|===
| link:afx-architecture-storage-efficiency.html[Previous: Storage efficiency]
>| link:afx-architecture-flexgroup.html[Next: FlexGroup management improvements]
|===
