---
sidebar: sidebar
permalink: afx/afx-architecture.html
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated
summary: "NetApp AFX introduces significant architectural differences from unified ONTAP in how storage is presented, how nodes interact with disks, and how capacity is managed."
---

= How NetApp AFX architecture differs from unified ONTAP
:icons: font
:imagesdir: ../media/afx/

[.lead]
NetApp AFX introduces significant architectural differences from unified ONTAP in how storage is presented, how nodes interact with disks, and how capacity is managed.

Previously, we showed a general picture of how unified ONTAP architecture delivers file, object, and block data storage via directly connected HA pairs that own their own sets of disks and present physical capacity via aggregates of disks. In this section, we'll discuss some of the major differences between unified ONTAP and NetApp AFX architectures in further detail.

== How to tell if a system is running NetApp AFX

The main way to see if your system is running NetApp AFX is to run the following command:

-----------------
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
-----------------

Another clue is the new Storage Availability Zone, but that is also a concept available to NetApp All-SAN Arrays (ASA). You can see your capacity via that command.

----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----

== Architecture topics

* link:afx-architecture-node-disk.html[Node-to-disk relationships]
* link:afx-architecture-capacity-pool.html[Single capacity pool]
* link:afx-architecture-nvram-ha.html[Replicated NVRAM and HA failover behavior]
* link:afx-architecture-independent-scale.html[Independent, linear scale]
* link:afx-architecture-raid.html[RAID changes]
* link:afx-architecture-storage-efficiency.html[Storage efficiency]
* link:afx-architecture-feature-support.html[ONTAP feature support changes]
* link:afx-architecture-flexgroup.html[FlexGroup management improvements]
* link:afx-architecture-volume-moves.html[Volume moves]
* link:afx-architecture-cluster-scale.html[Cluster scale]
* link:afx-architecture-root-volume.html[Root volume changes]
* link:afx-remove-nodes.html[How to remove AFX nodes]

[cols="1,1",frame=none,grid=none]
|===
| link:afx-whats-new.html[Previous]
>| link:afx-architecture-node-disk.html[Next: Node-to-disk relationships]
|===
